apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkblog
  labels:
    app: nkblog
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nkblog
  template:
    metadata:
      labels:
        name: nkblog
    spec:
      containers:
        - name: nkblog
          image: astronik/nkblog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
